Repository at-tienle2/Todo-PWA, pull requests merged in 2019-10, with the labels that each got.

#8 Making UI for list todo
  todo-vue-pwa/src/assets/styling/base/_variables.scss
  todo-vue-pwa/src/assets/styling/modules/_all.scss
  todo-vue-pwa/src/assets/styling/modules/_checkbox.scss
  todo-vue-pwa/src/assets/styling/pages/_all.scss
  todo-vue-pwa/src/assets/styling/pages/_form.scss
  todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
  todo-vue-pwa/src/components/features/ListTodo.vue
Labels: [Status] Reviewed, [Type] Feature

#11 Implement logic for list todo
  todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
  todo-vue-pwa/src/components/features/ListTodo.vue
  todo-vue-pwa/src/store/getters.ts
  todo-vue-pwa/src/store/state.ts
Labels: [Status] Reviewed, [Type] Feature

#6 [MANH] Footer UI
  todo-vue-pwa/src/assets/styling/base/_all.scss
  todo-vue-pwa/src/assets/styling/base/_base.scss
  todo-vue-pwa/src/assets/styling/base/_extends.scss
  todo-vue-pwa/src/assets/styling/base/_function.scss
  todo-vue-pwa/src/assets/styling/base/_mixins.scss
  todo-vue-pwa/src/assets/styling/base/_variables.scss
  todo-vue-pwa/src/assets/styling/layout/_footer.scss
  todo-vue-pwa/src/assets/styling/modules/_buttons.scss
  todo-vue-pwa/src/assets/styling/modules/_checkbox.scss
  todo-vue-pwa/src/assets/styling/state/_state.scss
  todo-vue-pwa/src/components/Todo.vue
  todo-vue-pwa/src/components/shared/Footer.vue
  todo-vue-pwa/src/store/state.ts
Labels: [Status] Reviewed, [Type] Feature

#12 Implement logic for add new
  todo-vue-pwa/src/components/features/Form.vue
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/mutations.ts
Labels: [Status] Reviewed, [Type] Feature

#13 Implement filter
  todo-vue-pwa/src/assets/styling/modules/_buttons.scss
  todo-vue-pwa/src/components/features/ListTodo.vue
  todo-vue-pwa/src/components/shared/Footer.vue
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/getters.ts
  todo-vue-pwa/src/store/mutations.ts
  todo-vue-pwa/src/store/state.ts
Labels: [Status] Fixed, [Type] Feature

#16 Responsive for app
  todo-vue-pwa/src/assets/styling/base/_variables.scss
  todo-vue-pwa/src/assets/styling/layout/_header.scss
  todo-vue-pwa/src/assets/styling/layout/_layout.scss
  todo-vue-pwa/src/components/Todo.vue
  todo-vue-pwa/src/components/features/Form.vue
  todo-vue-pwa/src/components/features/ListTodo.vue
Labels: [Status] Fixed, [Type] Task

#14 Show message no task
  todo-vue-pwa/src/assets/styling/modules/_buttons.scss
  todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
  todo-vue-pwa/src/components/features/ListTodo.vue
Labels: [Status] Fixed, [Type] Task

#15 Disabled button if it is current filter
  todo-vue-pwa/src/assets/styling/modules/_buttons.scss
  todo-vue-pwa/src/components/features/Form.vue
  todo-vue-pwa/src/components/shared/Footer.vue
Labels: [Status] Reviewed, [Type] Task

#17 Add transition
  todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
  todo-vue-pwa/src/components/features/ListTodo.vue
Labels: [Status] Fixed, [Type] Task

#19 Change text total task
  todo-vue-pwa/src/components/features/ListTodo.vue
Labels: [Status] Reviewed, [Type] Task

#20 Change id of item
  todo-vue-pwa/src/components/features/ListTodo.vue
Labels: [Status] Reviewed, [Type] Task

#21 Update UI for app
  todo-vue-pwa/src/assets/styling/layout/_footer.scss
  todo-vue-pwa/src/assets/styling/pages/_form.scss
  todo-vue-pwa/src/components/features/Form.vue
  todo-vue-pwa/src/components/shared/Footer.vue
Labels: [Status] Fixed, [Type] Task

#22 [Logic] Update status logic
  todo-vue-pwa/src/components/features/ListTodo.vue
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/mutations.ts
Labels: [Status] Fixed, [Type] Feature

#23 [Logic] Remove todo
  todo-vue-pwa/src/components/features/ListTodo.vue
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/mutations.ts
Labels: [Status] Fixed, [Type] Feature, [Type] Task

#24 Remove completed
  todo-vue-pwa/src/components/features/ListTodo.vue
  todo-vue-pwa/src/components/shared/Footer.vue
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/getters.ts
  todo-vue-pwa/src/store/mutations.ts
Labels: [Status] Reviewed, [Type] Feature

#25 Improve function
  todo-vue-pwa/src/store/mutations.ts
Labels: [Status] Reviewed, [Type] Task

#26 Change animation
  todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
  todo-vue-pwa/src/store/mutations.ts
Labels: [Status] Reviewed, [Type] Task

#27 [Task] [UI] Responsive on desktop view
  todo-vue-pwa/src/assets/styling/base/_base.scss
  todo-vue-pwa/src/assets/styling/base/_variables.scss
  todo-vue-pwa/src/assets/styling/layout/_footer.scss
  todo-vue-pwa/src/assets/styling/layout/_header.scss
  todo-vue-pwa/src/assets/styling/layout/_layout.scss
  todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
  todo-vue-pwa/src/store/mutations.ts
Labels: [Status] New, [Type] Feature, [Type] Task

#28 Install and add firebase
  todo-vue-pwa/.firebase/hosting.ZGlzdA.cache
  todo-vue-pwa/.firebaserc
  todo-vue-pwa/firebase.json
  todo-vue-pwa/package-lock.json
  todo-vue-pwa/package.json
  todo-vue-pwa/src/main.ts
Labels: [Status] Fixed, [Type] Task

#29 Create router for app
  todo-vue-pwa/src/App.vue
  todo-vue-pwa/src/components/HelloWorld.vue
  todo-vue-pwa/src/main.ts
  todo-vue-pwa/src/router.ts
  todo-vue-pwa/src/router/index.js
  todo-vue-pwa/src/router/index.ts
  todo-vue-pwa/src/views/About.vue
  todo-vue-pwa/src/views/Home.vue
  todo-vue-pwa/src/views/Todo.vue
Labels: [Status] Reviewed, [Type] Task

#30 Create auth component
  todo-vue-pwa/.firebase/hosting.ZGlzdA.cache
  todo-vue-pwa/src/assets/styling/base/_base.scss
  todo-vue-pwa/src/assets/styling/base/_variables.scss
  todo-vue-pwa/src/assets/styling/pages/_all.scss
  todo-vue-pwa/src/assets/styling/pages/_auth.scss
  todo-vue-pwa/src/components/features/SignIn.vue
  todo-vue-pwa/src/components/features/SignUp.vue
  todo-vue-pwa/src/router/index.ts
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/mutations.ts
  todo-vue-pwa/src/store/state.ts
  todo-vue-pwa/src/views/Auth.vue
Labels: [Status] Fixed, [Type] Task

#31 Using firebase to add, update, delete, remove
  todo-vue-pwa/src/components/features/ListTodo.vue
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/getters.ts
  todo-vue-pwa/src/store/mutations.ts
  todo-vue-pwa/src/store/state.ts
Labels: [Status] Fixed, [Type] Feature
