Repository at-tienle2/Todo-PWA, pull requests merged in 2019-11, with the labels that each got.

#32 Add loading screen
  todo-vue-pwa/src/App.vue
  todo-vue-pwa/src/assets/styling/modules/_all.scss
  todo-vue-pwa/src/assets/styling/modules/_loading.scss
  todo-vue-pwa/src/assets/styling/pages/_auth.scss
  todo-vue-pwa/src/components/features/ListTodo.vue
  todo-vue-pwa/src/components/features/SignIn.vue
  todo-vue-pwa/src/components/features/SignUp.vue
  todo-vue-pwa/src/components/shared/Loading.vue
Labels: [Status] Fixed, [Type] Task

#33 Order by created date
  todo-vue-pwa/src/store/mutations.ts
Labels: [Status] Fixed, [Type] Feature

#34 Task/20191106 manh signout
  todo-vue-pwa/package-lock.json
  todo-vue-pwa/src/assets/styling/base/_variables.scss
  todo-vue-pwa/src/assets/styling/layout/_header.scss
  todo-vue-pwa/src/assets/styling/pages/_auth.scss
  todo-vue-pwa/src/components/features/SignIn.vue
  todo-vue-pwa/src/components/features/SignUp.vue
  todo-vue-pwa/src/components/shared/Header.vue
  todo-vue-pwa/src/router/index.ts
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/getters.ts
  todo-vue-pwa/src/store/mutations.ts
  todo-vue-pwa/src/store/state.ts
Labels: [Status] Reopened, [Type] Feature, [Type] Task

#35 Change auth page
  todo-vue-pwa/.firebase/hosting.ZGlzdA.cache
  todo-vue-pwa/src/assets/styling/modules/_all.scss
  todo-vue-pwa/src/assets/styling/modules/_tabs.scss
  todo-vue-pwa/src/assets/styling/pages/_auth.scss
  todo-vue-pwa/src/components/features/ListTodo.vue
  todo-vue-pwa/src/components/features/SignIn.vue
  todo-vue-pwa/src/components/features/SignUp.vue
  todo-vue-pwa/src/components/shared/Header.vue
  todo-vue-pwa/src/main.ts
  todo-vue-pwa/src/router/index.ts
  todo-vue-pwa/src/store/actions.ts
  todo-vue-pwa/src/store/mutations.ts
  todo-vue-pwa/src/store/state.ts
  todo-vue-pwa/src/views/LogIn.vue
  todo-vue-pwa/src/views/SignUp.vue
Labels: [Status] Fixed, [Type] Task
